apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-depl
spec:
  replicas: 1

  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: vijay010498/hasura-ui-service
          env:
            - name: MONGO_URI
              value: 'mongodb://service-mongo-srv:27017/hasura'
---
apiVersion: v1
kind: Service
metadata:
  name: service-srv
spec:
  selector:
    app: service
  ports:
    - name: service
      protocol: TCP
      port: 3000
      targetPort: 3000
