name: tests-auth

on:
  pull_request:
    paths:
      - 'service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd service && npm install && npm run test:ci
